name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '42 15 * * *'

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - '7.3'
          - '7.4'
          - '8.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          ini-values: zend.assertions=1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-
          restore-keys: ${{ runner.os }}-composer-

      - name: Create BEAR.Sunday skeleton app
        run: composer create-project bear/skeleton app dev-dev --prefer-source --no-interaction --no-progress

      - name: Run ray/aop test suite
        run: cd ./app/vendor/ray/aop && git chackout 2.x

      - name: Run ray/di test suite
        run: cd ./app/vendor/ray/di && git chackout 2.x

      - name: Run BEAR.Sunday application
        run: php app/bin/page.php get /
